### ISSUE TITLE
android mvp checklist

### ISSUE THREAD

**Issue by javamonn** [literal-io/literal#31]
Prep:
- [x] Fix icon image in share target
- [x] Fix launch screen icon image
- [x] Set up staging environment in separate aws account
- [x] apollo-link-analytics
  - identify
  - install / uninstall in native
- [x] sentry
- [x] handle tag deletion edge cases 
  - delete tag when viewing in annotation collection (paginate to next item)
  - delete tag of last annotation in annotation collection (revert to recent)
- [x] fix agent creation
- [x] Wire up create from file in-js
- [x] migrate android to use /private storage uploads
- [x] Some sort of tag affordance
- [x] Update onboarding annotations
- [x] [device] fix zindex / background issue when creating annotation from text
- [x] [device] fix create tags with spaces
- [x] [device] fix create from text share target
- [x] [device] fix create annotation
- [x] privacy policy
- [ ] GPL
- [x] Overhaul create from external target
  - [x] remove playwright driver, simplify types
  - [x] ~pdfjs sites to simulate pdf (some way to load via url, render all pages)~ (punting into separate task #36)
  - [x] batch repeated screenshots to same url
  - [x] dockerize and script to run multiple containers on elastic beanstalk (worker environment?)
  - [x] if image crop fails to find highlight regions, fallback to just ocr entire image

Post:
- [ ] Mailing list for google form submissions, basic email templates
- [ ] Public roadmap
- [ ] Update index to route to appstore on android
